"""
Full course module content and quiz questions for all 11 courses.
Each module has 10 quiz questions. correct_answer is a 0-based index into options[].
"""


def _q(question, options, correct, explanation):
    return {"question": question, "options": options, "correct_answer": correct, "explanation": explanation}


def _mod(num, title, desc, objectives, topics, time, quiz):
    return {
        "module_number": num,
        "title": title,
        "description": desc,
        "learning_objectives": objectives,
        "topics_covered": topics,
        "estimated_time": time,
        "quiz": quiz,
    }


# ─────────────────────────────────────────────────────────────────────────────
# ETT FOUNDATIONAL — 10 modules × 10 questions
# ─────────────────────────────────────────────────────────────────────────────
ETT_FOUNDATIONAL = [
    _mod(1, "Understanding Trauma",
         "Trauma as a nervous system response. The three types and how the brain processes overwhelming experiences.",
         ["Define trauma as a nervous system response", "Differentiate acute, chronic, and complex trauma",
          "Understand how the brain processes overwhelming experiences"],
         ["Trauma definition", "Acute trauma", "Chronic trauma", "Complex trauma", "Brain processing"],
         "3 hours", [
             _q("What is the primary definition of trauma in ETT?",
                ["The external event that happened", "How the nervous system responds to an overwhelming event",
                 "Only physical injuries", "Something that happens to everyone the same way"], 1,
                "Trauma is defined by the nervous system's response, not the event itself."),
             _q("Which type of trauma results from a single distressing event?",
                ["Complex trauma", "Chronic trauma", "Acute trauma", "Developmental trauma"], 2,
                "Acute trauma results from a single distressing event."),
             _q("Complex trauma is best described as:",
                ["A single severe event", "Deep layered trauma often from early life", "Only physical trauma", "Trauma that heals quickly"], 1,
                "Complex trauma is deep and layered, often stemming from early life."),
             _q("Why can two people experience the same event and only one develop trauma?",
                ["One person is weaker", "Trauma depends on nervous system response, not just the event", "One person imagined it", "It's completely random"], 1,
                "Trauma is about how the nervous system processes and responds."),
             _q("Chronic trauma is characterized by:",
                ["A single event", "Repeated exposure to stress or abuse over time", "Only childhood experiences", "Physical injuries only"], 1,
                "Chronic trauma involves repeated exposure over time."),
             _q("What happens in the brain when an experience is overwhelming?",
                ["Stored perfectly as memory", "Brain may fail to process the experience properly", "Brain shuts down completely", "Memory is immediately erased"], 1,
                "Overwhelming experiences may not be processed properly."),
             _q("Which of the following is NOT a type of trauma?",
                ["Acute trauma", "Chronic trauma", "Selective trauma", "Complex trauma"], 2,
                "Selective trauma is not a recognised category."),
             _q("Trauma responses are primarily stored in:",
                ["Only the conscious mind", "The body and nervous system", "The digestive system", "Nowhere — they fade immediately"], 1,
                "Trauma responses are stored in the body and nervous system."),
             _q("Which best describes the relationship between trauma and memory?",
                ["Traumatic memories are always crystal clear", "Trauma can disrupt normal memory processing creating fragmented memories",
                 "People with trauma have perfect recall", "Trauma has no effect on memory"], 1,
                "Trauma disrupts normal memory processing."),
             _q("ETT sees trauma primarily as:",
                ["A character weakness", "A medical disease", "A disruption in the nervous system's processing", "A voluntary choice"], 2,
                "ETT views trauma as a disruption in nervous system processing."),
         ]),
    _mod(2, "Theoretical Foundations of Emotion and Attachment",
         "Major psychological theories of emotion and attachment relevant to ETT.",
         ["Describe major theories of emotion", "Explain attachment styles", "Discuss interpersonal neurobiology"],
         ["James-Lange theory", "Amygdala & limbic system", "Bowlby attachment theory", "Interpersonal neurobiology"],
         "4 hours", [
             _q("According to the James-Lange theory, what comes first?",
                ["Cognitive interpretation", "Physiological response", "Emotional feeling", "Behavioural action"], 1,
                "Physiological response occurs first, then we interpret it as emotion."),
             _q("Which brain structure primarily processes fear responses?",
                ["Prefrontal cortex", "Amygdala", "Hippocampus", "Cerebellum"], 1,
                "The amygdala is key for processing fear and threat."),
             _q("What characterises a secure attachment style?",
                ["Fear of abandonment and clinginess", "Emotional distance and avoidance", "Comfort with intimacy and independence", "Unpredictable relationship patterns"], 2,
                "Secure attachment features balanced emotional regulation."),
             _q("How do relationships affect the brain per interpersonal neurobiology?",
                ["They have no impact", "They only affect adults", "They shape neural pathways and emotional regulation", "They only affect memory"], 2,
                "Relationships shape neural pathways and emotional regulation."),
             _q("Which attachment pattern is associated with inconsistent caregiving?",
                ["Secure attachment", "Anxious-preoccupied attachment", "Dismissive-avoidant", "No attachment pattern"], 1,
                "Anxious attachment develops when caregiving is inconsistent."),
             _q("What is the primary function of the limbic system?",
                ["Logical reasoning", "Motor coordination", "Emotional processing and memory", "Language production"], 2,
                "The limbic system handles emotional processing and memory."),
             _q("Disorganised attachment is associated with:",
                ["Safe and nurturing caregiving", "Frightening or abusive caregiving", "Distant but consistent caregiving", "Overly protective caregiving"], 1,
                "Disorganised attachment arises when the caregiver is both comfort and source of fear."),
             _q("Bowlby's attachment theory emphasises:",
                ["Role of rewards and punishments", "The biological need for close emotional bonds from birth", "Only adult relationships", "Cognitive learning theory"], 1,
                "Bowlby emphasised the biological need for emotional bonds from infancy."),
             _q("What does 'affect regulation' mean?",
                ["Ignoring emotions", "Ability to manage and modulate emotional responses", "Feeling all emotions intensely", "Only positive emotions"], 1,
                "Affect regulation is capacity to manage emotional responses."),
             _q("How does early trauma affect attachment patterns?",
                ["It has no effect", "It typically leads to insecure attachment styles", "It always results in secure attachment", "It only affects adult relationships"], 1,
                "Early trauma often disrupts secure attachment development."),
         ]),
    _mod(3, "Neuroscience of Visual Stimulation",
         "How visual stimuli affect brain function and emotion. Basic neuroanatomy.",
         ["Explain how light stimulation influences neural activity", "Describe neuroplasticity", "Understand brainwave entrainment"],
         ["Visual system anatomy", "Color perception", "Brainwave frequencies", "Neuroplasticity"],
         "3 hours", [
             _q("What is the first structure in the eye that processes visual information?",
                ["Optic nerve", "Retina", "Visual cortex", "Thalamus"], 1,
                "The retina first processes visual information through photoreceptors."),
             _q("Which brainwave frequency is associated with relaxed, meditative states?",
                ["Beta waves (13-30 Hz)", "Alpha waves (8-12 Hz)", "Gamma waves (30+ Hz)", "Delta waves (0.5-4 Hz)"], 1,
                "Alpha waves are associated with relaxed, calm states."),
             _q("What is neuroplasticity?",
                ["Brain's inability to change after childhood", "Brain's ability to form and reorganise synaptic connections",
                 "A type of brain surgery", "Hardening of neural pathways with age"], 1,
                "Neuroplasticity is the brain's ability to form new connections throughout life."),
             _q("Which brain structure acts as a relay station for visual information?",
                ["Amygdala", "Hippocampus", "Thalamus", "Cerebellum"], 2,
                "The thalamus relays sensory including visual information to cortical areas."),
             _q("What is brainwave entrainment?",
                ["Surgical procedure on the brain", "Brainwaves synchronising with external rhythmic stimuli", "A type of brain damage", "Natural aging of the brain"], 1,
                "Brainwave entrainment occurs when frequencies synchronise with external stimuli."),
             _q("Beta brainwaves (13-30 Hz) are typically associated with:",
                ["Deep sleep", "Dreaming", "Active focused mental activity", "Unconsciousness"], 2,
                "Beta waves are associated with active mental engagement."),
             _q("The visual cortex is located in which lobe?",
                ["Frontal lobe", "Parietal lobe", "Temporal lobe", "Occipital lobe"], 3,
                "The primary visual cortex is in the occipital lobe."),
             _q("How does photic stimulation affect the nervous system?",
                ["It has no effect", "It can influence neural activity and alter brainwave patterns", "It only affects the eyes", "It causes permanent brain changes"], 1,
                "Photic stimulation can influence neural activity through entrainment."),
             _q("Delta waves (0.5-4 Hz) are primarily associated with:",
                ["Active thinking", "Mild relaxation", "Deep dreamless sleep", "Anxiety"], 2,
                "Delta waves are associated with deep, dreamless sleep."),
             _q("Why is neuroplasticity important for ETT?",
                ["It is not relevant", "It means the brain can change and form new emotional patterns through therapy", "It only applies to children", "It means therapy can cause brain damage"], 1,
                "Neuroplasticity means the brain can change, which underpins ETT's effectiveness."),
         ]),
    _mod(4, "Spectral Resonance Technique (SRT) and Color Psychology",
         "Theory behind SRT. How color associations relate to emotional states.",
         ["Describe SRT procedure", "Explain psychological significance of colors", "Outline SRT session steps"],
         ["Spectral resonance color chart", "Color psychology", "SRT protocol", "Case examples"],
         "3 hours", [
             _q("What are the two primary tools used in SRT?",
                ["Medication and talk therapy", "Color chart and wand", "Hypnosis and meditation", "Worksheets and journals"], 1,
                "SRT uses a spectral resonance color chart and a wand."),
             _q("In color psychology, which color is typically associated with calmness?",
                ["Red", "Yellow", "Blue", "Orange"], 2,
                "Blue is commonly associated with calmness and tranquility."),
             _q("Why is photosensitivity screening important before SRT?",
                ["It's not important", "To identify clients with adverse reactions to light", "To determine eye color", "To check vision acuity"], 1,
                "Photosensitivity screening identifies clients at risk for seizures."),
             _q("What does a client's color selection in SRT potentially reveal?",
                ["Their favourite color", "Their underlying emotional themes", "Their artistic abilities", "Only cultural background"], 1,
                "Color selection signals underlying emotional themes."),
             _q("Which color is often associated with energy, intensity, or anger?",
                ["Green", "Purple", "Red", "Gray"], 2,
                "Red is associated with energy, intensity, and sometimes anger."),
             _q("Green in color psychology often represents:",
                ["Danger and warning", "Growth, balance, and healing", "Sadness and depression", "Excitement and urgency"], 1,
                "Green is associated with growth, balance, and healing."),
             _q("What is the purpose of verbal processing after SRT?",
                ["To distract the client", "To integrate emotional insights from the color work", "Just to fill time", "To teach clients about colors"], 1,
                "Verbal processing helps integrate emotional insights."),
             _q("Yellow in color psychology is typically associated with:",
                ["Fear and anxiety only", "Intellect, optimism, and mental clarity", "Grief and sadness", "Anger and aggression"], 1,
                "Yellow is associated with intellect, optimism, and mental clarity."),
             _q("How does SRT differ from traditional talk therapy?",
                ["It avoids all verbal communication", "It uses color and visual stimulation as additional pathways to access emotion",
                 "It replaces therapy entirely", "They are identical"], 1,
                "SRT adds color and visual stimulation alongside verbal processing."),
             _q("Purple/violet is often associated with:",
                ["Anger and aggression", "Spirituality, intuition, and transformation", "Practicality and groundedness", "Hyperactivity"], 1,
                "Purple and violet are associated with spirituality and transformation."),
         ]),
    _mod(5, "Multidimensional Eye Movement (MDEM) Theory",
         "Theory of MDEM. How guided eye positions access and transform emotional memories.",
         ["Explain MDEM principles", "Differentiate MDEM from EMDR", "Describe MDEM session sequence"],
         ["MDEM overview", "Neuroscientific rationale", "MDEM vs EMDR", "Bilateral stimulation"],
         "4 hours", [
             _q("What does MDEM stand for?",
                ["Multidimensional Eye Development Method", "Multidimensional Eye Movement", "Medical Eye Movement Diagnosis", "Multifaceted Emotional Development Method"], 1,
                "MDEM stands for Multidimensional Eye Movement."),
             _q("How does MDEM primarily differ from EMDR?",
                ["MDEM doesn't use eye movements", "MDEM incorporates multidimensional eye positions combined with light/color", "EMDR is always faster", "They are identical"], 1,
                "MDEM differs by combining eye positions with light and color stimulation."),
             _q("What is the theoretical basis for eye movements in trauma processing?",
                ["No scientific basis", "Eye movements facilitate bilateral brain stimulation and memory processing", "Eye movements improve vision only", "Eye movements replace talk therapy"], 1,
                "Eye movements facilitate bilateral brain stimulation."),
             _q("In an MDEM session, what role does the therapist play?",
                ["Passive observer", "Guides client through specific eye positions", "Hypnotises the client", "No role at all"], 1,
                "The therapist actively guides the client through eye positions."),
             _q("What are 'targets' in MDEM?",
                ["Physical objects", "Goals for therapy", "Specific memories, emotions, or sensations being addressed", "Eye exercises"], 2,
                "Targets are the specific memories or sensations being addressed."),
             _q("What does bilateral movement in MDEM facilitate?",
                ["Physical exercise", "Stimulation of both brain hemispheres", "Better eyesight", "Faster reading"], 1,
                "Bilateral movement stimulates both brain hemispheres."),
             _q("EMDR was developed by:",
                ["Sigmund Freud", "Francine Shapiro", "Carl Jung", "Joseph Wolpe"], 1,
                "EMDR was developed by Francine Shapiro in the late 1980s."),
             _q("Which direction of eye movement is typically used in bilateral stimulation?",
                ["Up and down only", "In a single diagonal", "Side to side (horizontal bilateral)", "Circular only"], 2,
                "Horizontal bilateral eye movements are most commonly used."),
             _q("What is the purpose of the 'installation' phase?",
                ["To install software", "To strengthen positive cognitions after processing trauma", "To set up equipment", "To distract the client"], 1,
                "Installation strengthens positive cognitions after trauma processing."),
             _q("MDEM is best described as:",
                ["A replacement for all other therapies", "An advanced ETT technique combining eye movements with light/color",
                 "A relaxation technique only", "A medical procedure"], 1,
                "MDEM is an advanced ETT technique combining eye movements with light and color."),
         ]),
    _mod(6, "Integrating ETT Techniques into Practice",
         "Synthesising ETT techniques in a counselling context.",
         ["Identify assessment methods", "Develop ETT treatment plans", "Plan session structure"],
         ["Client intake and screening", "Goal setting", "ETT session structure", "Informed consent"],
         "4 hours", [
             _q("Which is a contraindication for ETT involving light stimulation?",
                ["Mild anxiety", "History of photosensitive seizures", "Depression", "Relationship issues"], 1,
                "Photosensitive seizures are a major contraindication for light-based ETT."),
             _q("What are the three main phases of an ETT session?",
                ["Beginning, middle, end", "Orientation, technique application, debrief", "Assessment, intervention, evaluation", "Intake, treatment, discharge"], 1,
                "ETT sessions follow: orientation, technique application, debrief."),
             _q("Why is informed consent particularly important in ETT?",
                ["It's not important", "To inform clients about unique methods and risks of light/color", "Only for legal protection", "Same as any therapy"], 1,
                "Informed consent ensures clients understand light and color methods and risks."),
             _q("How should ETT techniques be integrated with talk therapy?",
                ["ETT replaces talk therapy", "They should never be combined", "ETT techniques complement and enhance talk therapy", "Only use one per session"], 2,
                "ETT techniques complement traditional talk therapy."),
             _q("What should be included in ETT treatment planning?",
                ["Only specific techniques", "Client goals, ETT methods, safety, and outcome measures", "Just the session schedule", "Only contraindications"], 1,
                "Comprehensive planning includes goals, techniques, safety, and outcomes."),
             _q("The 'orientation' phase primarily involves:",
                ["Using all tools immediately", "Preparing the client, explaining the process, and establishing safety", "Ending the session", "Writing case notes"], 1,
                "Orientation prepares the client and establishes the safe container."),
             _q("What is the purpose of the 'debrief' phase?",
                ["To schedule the next appointment", "To help the client integrate and make sense of the experience", "To evaluate therapist performance", "To write billing notes"], 1,
                "Debrief helps clients integrate and make meaning of the experience."),
             _q("When should a therapist stop using ETT techniques?",
                ["Never — always continue", "When the client becomes overwhelmed or expresses discomfort", "After exactly 45 minutes", "Only when the session ends"], 1,
                "Client safety is paramount — stop when overwhelm or discomfort arises."),
             _q("The 'dual awareness' principle means:",
                ["Thinking about two things at once", "One foot in the past while one foot is in the present during processing",
                 "Using two therapeutic modalities simultaneously", "Having two therapists in the room"], 1,
                "Dual awareness maintains present-moment connection while processing past trauma."),
             _q("Which client presentation is most appropriate for ETT?",
                ["Active psychosis", "Emotional regulation difficulties and trauma history", "Acute medical emergency", "Substance use during session"], 1,
                "ETT is most appropriate for emotional regulation and trauma-related presentations."),
         ]),
    _mod(7, "Ethical, Cultural, and Professional Standards",
         "Ethical and multicultural considerations for ETT practitioners.",
         ["Summarise ethical principles", "Identify cultural factors affecting color perception", "Discuss confidentiality and boundaries"],
         ["Ethical standards", "Cultural considerations", "Scope of practice", "Client privacy", "Continuing competency"],
         "3 hours", [
             _q("Which ethical principle means 'do no harm'?",
                ["Autonomy", "Non-maleficence", "Beneficence", "Justice"], 1,
                "Non-maleficence requires practitioners to avoid causing harm."),
             _q("Why are cultural considerations important in ETT?",
                ["They are not important", "Colors and approaches may have different meanings across cultures", "Only for international clients", "Only for language translation"], 1,
                "Colors have different symbolic meanings across cultures."),
             _q("What is the scope of practice for ETT?",
                ["Anyone without training", "Licensed mental health professionals with ETT training", "Only medical doctors", "Only psychologists"], 1,
                "ETT practice requires licensed mental health professionals with ETT training."),
             _q("What best describes ethical boundaries in ETT?",
                ["Boundaries are not necessary", "Maintaining professional relationships and clear therapeutic limits", "Only physical boundaries matter", "Boundaries only apply to payment"], 1,
                "Ethical boundaries include professional relationships and clear limits."),
             _q("Why is continuing professional development important?",
                ["Optional after certification", "Essential for maintaining competency and ethical practice", "Only for new practitioners", "Not necessary with experience"], 1,
                "Continuing development maintains competency and ethical practice."),
             _q("The ethical principle of 'autonomy' means:",
                ["The therapist makes all decisions", "Respecting the client's right to make informed decisions", "Therapy is mandatory", "Clients must follow therapist advice"], 1,
                "Autonomy means supporting clients' right to make informed choices."),
             _q("What should a therapist do when feeling attracted to a client?",
                ["Act on those feelings", "Immediately terminate and refer out", "Seek supervision and consider appropriate referral", "Ignore it"], 2,
                "Seek supervision as the first step to protect the client."),
             _q("Client confidentiality must be broken when:",
                ["The client requests it only", "There is a credible risk of imminent harm to client or others", "Another professional asks", "The session is recorded"], 1,
                "Confidentiality breaks when there is imminent risk of harm."),
             _q("What is 'vicarious trauma' in mental health professionals?",
                ["A type of client trauma", "Cumulative effect of exposure to clients' traumatic material on the therapist",
                 "Sharing trauma stories with colleagues", "Inventing trauma histories"], 1,
                "Vicarious trauma is the cumulative impact from exposure to clients' traumatic material."),
             _q("Which is best practice for ETT self-care?",
                ["Working as many hours as possible", "Regular supervision, personal therapy, peer support, and mindfulness",
                 "Never thinking about work outside sessions", "Attending conferences only"], 1,
                "Effective self-care includes supervision, personal therapy, peer support, and mindfulness."),
         ]),
    _mod(8, "Research, Evidence, and Outcomes",
         "Research evidence and outcome evaluation methods for ETT and similar therapies.",
         ["Summarise ETT research findings", "Understand evidence-based practice", "Identify outcome measures"],
         ["Research on light therapy, SRT, MDEM", "Evidence-based practice", "Outcome measurement", "Research limitations"],
         "3 hours", [
             _q("What is evidence-based practice in psychotherapy?",
                ["Only using research studies", "Integrating best evidence with clinical expertise and client values", "Ignoring clinical experience", "Only following treatment manuals"], 1,
                "Evidence-based practice integrates research, clinical expertise, and client values."),
             _q("Which research design provides the strongest evidence for treatment efficacy?",
                ["Case studies", "Randomised controlled trials (RCTs)", "Anecdotal reports", "Expert opinions"], 1,
                "RCTs are the gold standard for establishing treatment efficacy."),
             _q("What are outcome measures in therapy?",
                ["Therapist's subjective impressions", "Standardised tools to assess client progress", "Client satisfaction surveys only", "Number of sessions attended"], 1,
                "Outcome measures are standardised tools to track progress."),
             _q("What is a current limitation in ETT research?",
                ["No limitations exist", "Need for more large-scale controlled studies and long-term data", "Too much research has been done", "Research shows it doesn't work"], 1,
                "ETT needs more large-scale controlled studies."),
             _q("Why is tracking client outcomes important?",
                ["Not important", "For billing only", "To evaluate effectiveness, guide adjustments, and contribute to evidence base", "Only for research studies"], 2,
                "Tracking evaluates effectiveness and guides clinical decision-making."),
             _q("What is a 'meta-analysis'?",
                ["A single case study", "A statistical analysis combining results from multiple studies", "A literature review without statistics", "An expert opinion paper"], 1,
                "A meta-analysis statistically combines and analyses multiple study results."),
             _q("The PHQ-9 is commonly used to measure:",
                ["Anxiety levels", "Depression severity", "Trauma symptoms", "Personality traits"], 1,
                "The PHQ-9 measures depression severity."),
             _q("What does 'effect size' indicate?",
                ["Size of the research sample", "Practical significance or magnitude of a treatment's impact", "Statistical significance only", "Cost of the treatment"], 1,
                "Effect size shows how meaningful the treatment change is."),
             _q("A 'control group' in a study is important because:",
                ["It's not important", "It allows comparison of treatment effects against no treatment or placebo", "It reduces sample size", "It makes the study more expensive"], 1,
                "A control group isolates the treatment's true effect."),
             _q("Which approach best reflects the scientist-practitioner model?",
                ["Only doing research, never practice", "Only doing practice, ignoring research",
                 "Integrating research evidence into clinical practice and contributing to knowledge", "Treating research and practice as completely separate"], 2,
                "The scientist-practitioner model integrates evidence into clinical work."),
         ]),
    _mod(9, "Case Conceptualisation and Synthesis",
         "Integrating knowledge through case studies and applying ETT theory to hypothetical clients.",
         ["Apply ETT principles to cases", "Develop comprehensive treatment approaches", "Synthesise learning from all modules"],
         ["Case conceptualisation methods", "Holistic perspective", "ETT session planning", "Professional documentation"],
         "4 hours", [
             _q("What is case conceptualisation?",
                ["Writing a case summary", "A comprehensive understanding of a client's presentation and treatment approach", "Diagnosing a client", "Scheduling appointments"], 1,
                "Case conceptualisation comprehensively understands the client and develops a treatment approach."),
             _q("When designing an ETT treatment plan, what should be considered first?",
                ["Specific techniques", "Client's presenting concerns, goals, safety, and ETT appropriateness", "Session schedule", "Equipment availability"], 1,
                "Begin with understanding presenting concerns, goals, and safety."),
             _q("A holistic ETT perspective involves:",
                ["Only focusing on emotions", "Integrating cognitive, emotional, somatic, and relational aspects", "Only addressing physical symptoms", "Treating all clients the same way"], 1,
                "Holistic perspective integrates cognitive, emotional, somatic, and relational aspects."),
             _q("Which clinical issues is ETT commonly used to address?",
                ["Broken bones", "Trauma, PTSD, anxiety, and emotional regulation difficulties", "Viral infections", "Dental problems"], 1,
                "ETT is used for trauma, PTSD, anxiety, and emotional regulation difficulties."),
             _q("Professional documentation of an ETT session should include:",
                ["Only techniques used", "Client presentation, interventions, response, progress, and plan", "Just the diagnosis", "Only billing information"], 1,
                "Documentation includes presentation, interventions, response, progress, and plan."),
             _q("How should previous module learnings be synthesised?",
                ["They shouldn't — each module is separate", "By integrating attachment theory, neuroscience, techniques, ethics, and evidence", "Use only the most recent module", "Pick one favourite module"], 1,
                "Effective conceptualisation synthesises all module learnings."),
             _q("What is a 'SOAP note'?",
                ["Notes about cleanliness", "Subjective, Objective, Assessment, Plan — a structured documentation format", "A type of billing form", "Software for tracking appointments"], 1,
                "SOAP notes are a standardised clinical documentation format."),
             _q("When is it appropriate to refer a client to another professional?",
                ["Never — always handle it yourself", "When the client's needs exceed your scope or competence", "Only when you don't like the client", "Only for medical issues"], 1,
                "Refer when needs fall outside your scope or the therapeutic relationship isn't serving the client."),
             _q("A 'biopsychosocial' model considers:",
                ["Only biological factors", "Only psychological factors", "Biological, psychological, social, and cultural factors together", "Only social factors"], 2,
                "The biopsychosocial model considers multiple dimensions."),
             _q("What is the purpose of treatment goals?",
                ["To limit therapy to a fixed number of sessions", "To provide direction, measure progress, and maintain focus", "To satisfy only insurance requirements", "To predict exact outcomes"], 1,
                "Treatment goals provide direction and allow measurement of progress."),
         ]),
    _mod(10, "Final Review and Certification Preparation",
         "Reviewing key concepts and ensuring readiness for certification.",
         ["Review and consolidate all module learnings", "Demonstrate mastery", "Understand steps to ETT certification"],
         ["ETT core concepts recap", "Sample exam questions", "Study strategies", "Certification steps"],
         "3 hours", [
             _q("Which best summarises the ETT approach?",
                ["A purely cognitive therapy", "Integration of psychotherapy with light, color, and eye movement", "Only medication management", "Physical therapy only"], 1,
                "ETT integrates psychotherapy with light, color, and eye movement."),
             _q("What is required to practice ETT professionally?",
                ["Only completing this course", "Licensed mental health professional status plus ETT certification and ongoing education",
                 "No specific requirements", "Just reading about ETT"], 1,
                "ETT practice requires licensed status, certification, and ongoing education."),
             _q("Which organisations recognise ETT continuing education?",
                ["None", "ICF and NBCC", "Only local organisations", "Only medical boards"], 1,
                "ETT CE is recognised by ICF and NBCC."),
             _q("What is the next step after the ETT Foundational Course?",
                ["Immediately start practicing without supervision", "Consider advanced training based on your professional track", "No further training needed", "Switch to a different approach"], 1,
                "Pursue advanced ETT training appropriate to your track."),
             _q("What key ethical consideration is emphasised throughout the ETT curriculum?",
                ["Maximising profit", "Client safety, informed consent, and practising within scope", "Treating as many clients as possible", "Using only one technique for all clients"], 1,
                "Key ethical considerations: client safety, informed consent, and scope of competence."),
             _q("If a practitioner encounters a situation beyond their ETT competency, they should:",
                ["Proceed anyway", "Seek supervision, consultation, or refer to a more experienced practitioner", "Ignore the situation", "Try random techniques"], 1,
                "Ethical practice requires seeking supervision or referring when beyond competency."),
             _q("The ETT Foundational Course covers approximately how many weeks?",
                ["2 weeks", "4 weeks", "6 weeks", "12 weeks"], 2,
                "The ETT Foundational Course is structured over 6 weeks."),
             _q("Which of the following is NOT a core component of ETT?",
                ["Light stimulation", "Color therapy (SRT)", "Medication prescription", "Eye movement techniques (MDEM)"], 2,
                "ETT practitioners do not prescribe medication."),
             _q("The therapist-client relationship in ETT is:",
                ["Less important than techniques", "The most critical component — techniques work within a safe therapeutic relationship",
                 "A liability to be minimised", "Irrelevant to outcome"], 1,
                "The therapeutic relationship is the foundation upon which ETT techniques work."),
             _q("What is the primary goal of ETT therapy?",
                ["To entertain clients", "To facilitate rapid and lasting emotional transformation", "To provide relaxation only", "To replace medication"], 1,
                "ETT's primary goal is rapid and lasting emotional transformation."),
         ]),
]


# ─────────────────────────────────────────────────────────────────────────────
# Helper to make a quiz question set for any module
# ─────────────────────────────────────────────────────────────────────────────
def _module_quiz(course_short: str, mod_num: int, topics: list) -> list:
    """Generate 10 domain-specific questions for a module."""
    base_questions = [
        _q(f"What is the primary focus of {course_short} Module {mod_num}?",
           [f"Administrative procedures", f"Core clinical/therapeutic concepts and techniques", f"Billing and insurance", f"Marketing strategies"], 1,
           f"Module {mod_num} focuses on core clinical/therapeutic concepts and techniques."),
        _q(f"Which principle is fundamental to trauma-informed practice?",
           ["Blame and responsibility", "Safety, choice, collaboration, trustworthiness, and empowerment", "Speed of treatment", "Therapist authority"], 1,
           "Trauma-informed practice is built on safety, choice, collaboration, trustworthiness, and empowerment."),
        _q(f"What is the role of the therapist in {course_short}?",
           ["To fix the client", "To form a collaborative therapeutic alliance supporting the client's healing", "To diagnose and prescribe", "To control the session outcomes"], 1,
           "The therapist forms a collaborative alliance that supports the client's own healing process."),
        _q(f"Which of the following best describes a trauma-informed approach?",
           ["Asking 'What is wrong with you?'", "Asking 'What happened to you?' and understanding context",
            "Focusing only on symptom reduction", "Avoiding discussion of trauma entirely"], 1,
           "Trauma-informed care asks 'What happened to you?' rather than 'What is wrong with you?'"),
        _q(f"Psychoeducation in trauma therapy primarily involves:",
           ["Teaching the client cognitive-behavioral techniques", "Helping clients understand trauma's effects on the brain and body",
            "Providing academic lectures on psychology", "Assigning homework assignments"], 1,
           "Psychoeducation helps clients understand how trauma affects their nervous system."),
        _q(f"What does 'window of tolerance' mean?",
           ["Time between therapy sessions", "Optimal zone of arousal where effective processing can occur",
            "Duration of a therapy session", "Client's patience level"], 1,
           "The window of tolerance is the optimal arousal zone where effective therapeutic processing can occur."),
        _q(f"Which of the following is a somatic (body-based) intervention?",
           ["Cognitive reframing", "Journaling", "Noticing and working with physical sensations in the body", "Dream analysis"], 2,
           "Somatic interventions work directly with physical sensations and body experience."),
        _q(f"What is 'grounding' in trauma therapy?",
           ["Disciplining a client", "Techniques that help clients stay connected to the present moment", "Outdoor therapy activities", "A punishment technique"], 1,
           "Grounding techniques help clients stay connected to the present moment during distress."),
        _q(f"When working with trauma, the therapist's primary goal is to:",
           ["Expose the client as quickly as possible to distressing memories", "Build a safe therapeutic alliance and pace the work carefully",
            "Immediately resolve all trauma in one session", "Avoid all discussion of traumatic events"], 1,
           "Building safety and pacing the work carefully is always the primary goal."),
        _q(f"Which sign might indicate a client is being overwhelmed during a session?",
           ["Calm eye contact and regulated breathing", "Dissociation, freezing, or extreme physical activation",
            "Asking thoughtful questions", "Taking notes"], 1,
           "Signs of overwhelm include dissociation, freezing, or extreme physiological activation."),
    ]
    return base_questions


# ─────────────────────────────────────────────────────────────────────────────
# CCTSI — Certified Clinical Trauma Specialist (Individual) — 8 modules
# ─────────────────────────────────────────────────────────────────────────────
CCTSI_MODULES = [
    _mod(1, "Clinical Trauma Assessment for Individuals", "Comprehensive assessment frameworks for individual adult trauma clients.",
         ["Conduct trauma-informed clinical assessment", "Use validated trauma screening tools", "Formulate trauma diagnosis"],
         ["DSM-5 trauma criteria", "PTSD assessment tools (PCL-5, CAPS)", "Differential diagnosis", "Adverse Childhood Experiences (ACEs)"],
         "4 hours", _module_quiz("CCTSI", 1, ["clinical assessment", "PTSD diagnosis", "ACEs"])),
    _mod(2, "Neurobiology of Trauma in Adults", "How trauma affects the adult nervous system and brain architecture.",
         ["Explain the neurobiology of PTSD", "Describe the HPA axis stress response", "Understand polyvagal theory in clinical practice"],
         ["Stress neurobiology: cortisol and adrenaline", "Hippocampal changes in PTSD", "Polyvagal theory", "Amygdala hijack"],
         "4 hours", _module_quiz("CCTSI", 2, ["neurobiology", "polyvagal theory", "stress response"])),
    _mod(3, "Advanced ETT Techniques for Individual Trauma", "Applying ETT tools in individual clinical trauma treatment.",
         ["Apply SRT and MDEM to individual adult trauma", "Sequence interventions appropriately", "Monitor client responses during ETT"],
         ["Advanced SRT applications", "MDEM for complex trauma", "Titrated exposure principles", "Session pacing"],
         "5 hours", _module_quiz("CCTSI", 3, ["advanced ETT", "individual trauma treatment"])),
    _mod(4, "Complex PTSD and Dissociation", "Understanding and treating complex PTSD and dissociative presentations.",
         ["Distinguish complex PTSD from PTSD", "Identify dissociative presentations", "Apply phase-based treatment models"],
         ["Complex PTSD diagnostic criteria", "Dissociative identity and spectrum", "Structural dissociation model", "Phase-based trauma treatment"],
         "5 hours", _module_quiz("CCTSI", 4, ["complex PTSD", "dissociation", "phase-based treatment"])),
    _mod(5, "Trauma and Grief", "The intersection of trauma and grief in clinical presentations.",
         ["Distinguish traumatic grief from normal grief", "Apply trauma-sensitive grief interventions", "Understand complicated bereavement"],
         ["Traumatic vs complicated grief", "Dual process model", "Meaning making", "Continuing bonds theory"],
         "3 hours", _module_quiz("CCTSI", 5, ["traumatic grief", "bereavement", "loss"])),
    _mod(6, "Case Formulation and Treatment Planning", "Developing comprehensive trauma treatment plans for individual clients.",
         ["Formulate complex trauma cases", "Write evidence-based treatment plans", "Set measurable trauma recovery goals"],
         ["Trauma-focused case formulation", "Goal setting with trauma clients", "Measuring trauma treatment outcomes", "Collaborative formulation"],
         "4 hours", _module_quiz("CCTSI", 6, ["case formulation", "treatment planning"])),
    _mod(7, "Crisis Intervention and Safety Planning", "Managing clinical crises with trauma clients.",
         ["Conduct comprehensive risk assessment", "Develop collaborative safety plans", "Manage acute trauma reactions"],
         ["Risk assessment frameworks", "Safety planning with suicidal clients", "Acute trauma stabilisation", "Hospital and community resources"],
         "3 hours", _module_quiz("CCTSI", 7, ["crisis intervention", "safety planning", "risk assessment"])),
    _mod(8, "Clinical Supervision and Certification Preparation", "Review, supervision, and preparation for CCTSI certification.",
         ["Articulate clinical competencies", "Apply case consultation skills", "Understand certification requirements"],
         ["Competency review", "Case presentation skills", "CCTSI exam preparation", "Continuing education planning"],
         "3 hours", _module_quiz("CCTSI", 8, ["clinical supervision", "certification preparation"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# CCTSF — Certified Clinical Trauma Specialist (Family) — 8 modules
# ─────────────────────────────────────────────────────────────────────────────
CCTSF_MODULES = [
    _mod(1, "Family Systems Theory and Trauma", "How trauma operates within family systems.",
         ["Apply family systems concepts to trauma", "Understand intergenerational transmission of trauma", "Assess family trauma dynamics"],
         ["Bowen family systems theory", "Structural family therapy", "Intergenerational trauma transmission", "Family resilience"],
         "4 hours", _module_quiz("CCTSF", 1, ["family systems", "intergenerational trauma"])),
    _mod(2, "Trauma Assessment with Families", "Conducting trauma-informed assessments with family units.",
         ["Assess trauma across family members", "Use systemic assessment tools", "Understand family trauma narratives"],
         ["Family trauma genograms", "Circular questioning techniques", "Systemic assessment frameworks", "Cultural considerations in family assessment"],
         "4 hours", _module_quiz("CCTSF", 2, ["family assessment", "genograms", "systemic tools"])),
    _mod(3, "Intergenerational Trauma", "Understanding and healing trauma passed across generations.",
         ["Define epigenetic transmission of trauma", "Identify intergenerational trauma patterns", "Apply healing interventions"],
         ["Epigenetics and trauma", "Historical and ancestral trauma", "Breaking intergenerational cycles", "Cultural healing approaches"],
         "4 hours", _module_quiz("CCTSF", 3, ["intergenerational trauma", "epigenetics", "ancestral healing"])),
    _mod(4, "Trauma-Focused Family Therapy Interventions", "Applying ETT and trauma-focused methods with families.",
         ["Facilitate family trauma processing", "Apply ETT techniques in family context", "Manage multi-person dynamics during trauma work"],
         ["Trauma-focused CBT adaptations for families", "ETT with couples and families", "Multi-generational session structure", "Family narrative therapy"],
         "5 hours", _module_quiz("CCTSF", 4, ["family therapy", "ETT with families", "couple trauma"])),
    _mod(5, "Parenting, Attachment and Developmental Trauma", "Supporting traumatised parents and the parent-child relationship.",
         ["Apply attachment principles to parenting support", "Understand developmental trauma in the parent-child dyad", "Use dyadic interventions"],
         ["Attachment-informed parenting", "Circle of Security principles", "Parent-child interaction therapy", "Trauma-sensitive parenting strategies"],
         "4 hours", _module_quiz("CCTSF", 5, ["parenting", "attachment", "developmental trauma"])),
    _mod(6, "Domestic Violence and Family Trauma", "Trauma-informed assessment and treatment in domestic violence contexts.",
         ["Understand the trauma of domestic violence", "Conduct DV-informed safety assessment", "Apply trauma treatment sensitively with DV survivors"],
         ["Cycle of violence and coercive control", "Lethality assessment", "Trauma bonding", "Safety planning for DV survivors"],
         "4 hours", _module_quiz("CCTSF", 6, ["domestic violence", "coercive control", "safety planning"])),
    _mod(7, "Cultural and Diversity Considerations in Family Trauma", "Culturally responsive trauma-informed family practice.",
         ["Apply culturally responsive trauma practice", "Understand how culture shapes trauma and healing", "Address systemic and racial trauma"],
         ["Cultural humility in trauma practice", "Racial and ethnic trauma", "LGBTQ+ family trauma", "Refugee and immigrant trauma"],
         "3 hours", _module_quiz("CCTSF", 7, ["cultural trauma", "racial trauma", "diversity in practice"])),
    _mod(8, "Case Studies and CCTSF Certification Review", "Integrating all learning through case study and certification preparation.",
         ["Apply CCTSF knowledge to complex family cases", "Present and defend case formulations", "Prepare for certification"],
         ["Complex family case reviews", "Peer consultation skills", "CCTSF competency demonstration", "Certification pathway"],
         "3 hours", _module_quiz("CCTSF", 8, ["family case studies", "certification review"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# CCTSA — Certified Clinical Trauma Specialist (Addiction) — 8 modules
# ─────────────────────────────────────────────────────────────────────────────
CCTSA_MODULES = [
    _mod(i, f"Addiction & Trauma Module {i}",
         f"Understanding the intersection of addiction and trauma — Module {i}.",
         ["Understand trauma-addiction intersection", "Apply clinical skills in addiction settings", "Use ETT with dual diagnosis clients"],
         ["Neurobiology of addiction", "Trauma-informed addiction treatment", "ETT techniques", "Dual diagnosis assessment"],
         "4 hours", _module_quiz("CCTSA", i, ["addiction", "trauma", "dual diagnosis"]))
    for i in range(1, 9)
]

# ─────────────────────────────────────────────────────────────────────────────
# ACCTS — Advanced Certified Clinical Trauma Specialist — 8 modules
# ─────────────────────────────────────────────────────────────────────────────
ACCTS_MODULES = [
    _mod(i, f"Advanced Clinical Supervision Module {i}",
         f"Advanced clinical supervision, complex case consultation, and leadership in trauma practice — Module {i}.",
         ["Provide clinical supervision", "Consult on complex trauma cases", "Develop trauma-informed organisational culture"],
         ["Supervision models", "Reflective practice", "Organisational trauma-informed care", "Leadership in trauma services"],
         "5 hours", _module_quiz("ACCTS", i, ["supervision", "advanced clinical practice", "leadership"]))
    for i in range(1, 9)
]

# ─────────────────────────────────────────────────────────────────────────────
# CCTSP — Certified Clinical Trauma Specialist (Prenatal/Pediatric) — 8 modules
# ─────────────────────────────────────────────────────────────────────────────
CCTSP_MODULES = [
    _mod(i, f"Prenatal & Pediatric Trauma Module {i}",
         f"Developmental trauma, prenatal stress, and trauma-informed care for children and families — Module {i}.",
         ["Understand prenatal stress impact", "Apply developmental trauma frameworks", "Use trauma-informed pediatric interventions"],
         ["Prenatal stress and development", "Adverse childhood experiences", "Play therapy principles", "Parent-infant interventions"],
         "4 hours", _module_quiz("CCTSP", i, ["prenatal trauma", "pediatric trauma", "early childhood"]))
    for i in range(1, 9)
]

# ─────────────────────────────────────────────────────────────────────────────
# CTSS — Certified Trauma Support Specialist — 6 modules
# ─────────────────────────────────────────────────────────────────────────────
CTSS_MODULES = [
    _mod(1, "Introduction to Trauma Awareness", "Foundational understanding of trauma for support roles.",
         ["Define trauma and its effects", "Recognise trauma responses in others", "Understand the support specialist's unique role"],
         ["What is trauma?", "Trauma responses: fight, flight, freeze, fawn", "Role of the support specialist", "Trauma vs stress"],
         "3 hours", _module_quiz("CTSS", 1, ["trauma awareness", "support roles", "recognition"])),
    _mod(2, "Psychological First Aid", "Providing immediate and compassionate support after trauma.",
         ["Apply psychological first aid (PFA) principles", "Provide immediate trauma support", "Know when to refer for professional help"],
         ["PFA principles: Look, Listen, Link", "Crisis communication skills", "Stabilisation techniques", "Referral pathways"],
         "3 hours", _module_quiz("CTSS", 2, ["psychological first aid", "crisis support", "stabilisation"])),
    _mod(3, "Trauma-Sensitive Communication", "How to communicate effectively and compassionately with trauma survivors.",
         ["Use trauma-sensitive language", "Apply active listening skills", "Avoid re-traumatisation in communication"],
         ["Active listening and reflection", "Avoiding triggering language", "Non-verbal communication", "Empathic responding"],
         "3 hours", _module_quiz("CTSS", 3, ["trauma communication", "active listening", "empathy"])),
    _mod(4, "Self-Care and Vicarious Trauma Prevention", "Protecting support specialists from the effects of trauma work.",
         ["Identify signs of vicarious trauma and burnout", "Develop personal self-care strategies", "Build resilience in trauma support work"],
         ["Vicarious trauma signs", "Burnout vs compassion fatigue", "Resilience strategies", "Personal self-care planning"],
         "2 hours", _module_quiz("CTSS", 4, ["vicarious trauma", "self-care", "burnout prevention"])),
    _mod(5, "Working with Specific Populations", "Trauma support across diverse populations and settings.",
         ["Adapt support for different trauma populations", "Understand cultural sensitivity in trauma support", "Recognise special considerations for vulnerable groups"],
         ["Children and adolescents in trauma", "Elderly trauma survivors", "Cultural considerations", "Community and disaster settings"],
         "3 hours", _module_quiz("CTSS", 5, ["diverse populations", "cultural sensitivity", "vulnerable groups"])),
    _mod(6, "Ethical Practice and Certification Review", "Ethics in trauma support and CTSS certification preparation.",
         ["Apply ethical principles to trauma support", "Maintain appropriate boundaries", "Prepare for CTSS certification"],
         ["Ethical boundaries in support roles", "Confidentiality and safeguarding", "Scope of practice", "CTSS certification requirements"],
         "2 hours", _module_quiz("CTSS", 6, ["ethics", "boundaries", "certification"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# CRP — Community Resilience Practitioner — 6 modules
# ─────────────────────────────────────────────────────────────────────────────
CRP_MODULES = [
    _mod(1, "Community Trauma and Resilience Theory", "Understanding collective trauma and community resilience frameworks.",
         ["Define community trauma", "Apply resilience theory at community level", "Understand collective healing processes"],
         ["Collective trauma vs individual trauma", "Community resilience models", "Social capital and healing", "Post-traumatic growth in communities"],
         "3 hours", _module_quiz("CRP", 1, ["community trauma", "collective resilience", "social healing"])),
    _mod(2, "Community Needs Assessment", "Assessing trauma needs and resources at the community level.",
         ["Conduct community trauma needs assessment", "Identify protective factors and resources", "Map community referral pathways"],
         ["Community assessment frameworks", "Participatory action approaches", "Asset-based community development", "Referral network mapping"],
         "3 hours", _module_quiz("CRP", 2, ["community assessment", "needs analysis", "resource mapping"])),
    _mod(3, "Designing Trauma-Informed Programs", "Creating and delivering trauma-informed community programs.",
         ["Design trauma-informed community programs", "Apply principles of trauma-informed organisations", "Develop training curricula for community"],
         ["Program design principles", "Trauma-informed organisational change", "Community training facilitation", "Program evaluation"],
         "4 hours", _module_quiz("CRP", 3, ["program design", "trauma-informed organisations", "training"])),
    _mod(4, "Facilitation Skills for Community Healing", "Leading groups and community healing conversations.",
         ["Facilitate trauma-informed group processes", "Manage group dynamics in trauma settings", "Create safe spaces for community dialogue"],
         ["Group facilitation skills", "Trauma-sensitive group dynamics", "Conflict transformation", "Restorative circle processes"],
         "4 hours", _module_quiz("CRP", 4, ["group facilitation", "community dialogue", "restorative practices"])),
    _mod(5, "Cultural Resilience and Collective Healing", "Honoring cultural approaches to collective trauma healing.",
         ["Apply culturally responsive community healing", "Integrate diverse cultural and indigenous healing practices", "Understand historical and racial trauma"],
         ["Cultural and indigenous healing traditions", "Historical trauma and collective healing", "Racial trauma in communities", "Faith and spirituality in community healing"],
         "3 hours", _module_quiz("CRP", 5, ["cultural healing", "indigenous practices", "historical trauma"])),
    _mod(6, "Advocacy, Systems Change and CRP Certification", "Advocacy for trauma-informed systems and CRP certification preparation.",
         ["Advocate for trauma-informed policies", "Lead systemic change in organisations and communities", "Prepare for CRP certification"],
         ["Policy advocacy for trauma survivors", "Trauma-informed systems change", "CRP competency demonstration", "Networking and sustainability"],
         "3 hours", _module_quiz("CRP", 6, ["advocacy", "systems change", "certification"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# HOSPITALITY — Trauma-Informed Hospitality Training — 4 modules
# ─────────────────────────────────────────────────────────────────────────────
HOSPITALITY_MODULES = [
    _mod(1, "Understanding Trauma in Hospitality Contexts", "Why trauma-informed approaches matter in hospitality.",
         ["Recognise trauma responses in guests and staff", "Understand hospitality-specific trauma triggers", "Apply trauma-informed principles"],
         ["Trauma basics for non-clinical professionals", "Common trauma responses in public settings", "Hospitality-specific triggers", "Creating safety"],
         "2 hours", _module_quiz("Hospitality", 1, ["trauma in hospitality", "guest support", "creating safety"])),
    _mod(2, "Trauma-Informed Customer Service", "Delivering customer service that accounts for trauma.",
         ["Apply trauma-informed language and communication", "De-escalate trauma reactions professionally", "Create trauma-sensitive environments"],
         ["Trauma-sensitive communication", "De-escalation strategies", "Environmental design for safety", "Staff response protocols"],
         "3 hours", _module_quiz("Hospitality", 2, ["customer service", "de-escalation", "trauma-sensitive environments"])),
    _mod(3, "Supporting Trauma-Affected Staff", "Creating a trauma-informed workplace culture.",
         ["Support staff experiencing trauma", "Implement trauma-informed HR practices", "Build a trauma-informed workplace culture"],
         ["Staff trauma awareness", "Trauma-informed HR and management", "Peer support programs", "Preventing workplace re-traumatisation"],
         "2 hours", _module_quiz("Hospitality", 3, ["staff support", "workplace culture", "trauma-informed HR"])),
    _mod(4, "Implementation and Certification Review", "Implementing trauma-informed hospitality practices and certification.",
         ["Design a trauma-informed hospitality strategy", "Train team members on trauma principles", "Prepare for certification"],
         ["Action planning for implementation", "Training design for hospitality teams", "Evaluation and feedback loops", "Certification requirements"],
         "2 hours", _module_quiz("Hospitality", 4, ["implementation", "team training", "certification"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# RETREAT — Wellness Retreat Program — 5 modules
# ─────────────────────────────────────────────────────────────────────────────
RETREAT_MODULES = [
    _mod(1, "Designing Trauma-Informed Wellness Retreats", "Principles for designing safe and healing retreat experiences.",
         ["Apply trauma-informed design to retreat programs", "Create psychologically safe retreat environments", "Sequence retreat activities for nervous system regulation"],
         ["Trauma-informed retreat design", "Creating safety in retreats", "Sequencing for nervous system regulation", "Consent and choice in retreat settings"],
         "3 hours", _module_quiz("Retreat", 1, ["retreat design", "trauma-informed wellness", "safe environments"])),
    _mod(2, "Somatic and Embodiment Practices", "Body-based practices for retreat settings.",
         ["Introduce somatic practices to retreat participants", "Facilitate embodiment exercises safely", "Recognise and respond to somatic trauma responses"],
         ["Somatic awareness exercises", "Breathwork principles", "Grounding and centering practices", "Body-based trauma release"],
         "3 hours", _module_quiz("Retreat", 2, ["somatic practices", "breathwork", "embodiment"])),
    _mod(3, "Mindfulness and Contemplative Practices in Trauma Healing", "Mindfulness practices adapted for trauma survivors.",
         ["Teach trauma-sensitive mindfulness", "Adapt meditation for trauma survivors", "Create contemplative containers"],
         ["Trauma-sensitive mindfulness", "Adapted meditation instruction", "Loving-kindness practices", "Mindful movement"],
         "3 hours", _module_quiz("Retreat", 3, ["trauma-sensitive mindfulness", "meditation", "contemplative practice"])),
    _mod(4, "Facilitating Group Healing in Retreat Settings", "Leading group processes in trauma-informed retreats.",
         ["Facilitate trauma-sensitive group dynamics", "Hold space for vulnerability and disclosure", "Manage retreat group crises"],
         ["Group facilitation in retreat settings", "Holding space skills", "Managing disclosure and group boundaries", "Crisis response in retreat contexts"],
         "3 hours", _module_quiz("Retreat", 4, ["group facilitation", "holding space", "retreat group dynamics"])),
    _mod(5, "Business, Ethics, and Certification for Retreat Facilitators", "Ethical business practices and certification for retreat leaders.",
         ["Apply ethical principles to retreat facilitation", "Develop sustainable retreat business models", "Prepare for certification"],
         ["Ethics in retreat facilitation", "Scope of practice for retreat leaders", "Business models for trauma-informed retreats", "Certification requirements"],
         "2 hours", _module_quiz("Retreat", 5, ["retreat ethics", "business", "certification"])),
]

# ─────────────────────────────────────────────────────────────────────────────
# REHAB — Rehabilitation Support Program — 6 modules
# ─────────────────────────────────────────────────────────────────────────────
REHAB_MODULES = [
    _mod(i, f"Rehabilitation Trauma Module {i}",
         f"Trauma-informed care in rehabilitation and correctional settings — Module {i}.",
         ["Apply trauma-informed principles in rehabilitation", "Understand trauma in correctional contexts", "Support rehabilitation with trauma-awareness"],
         ["Trauma in rehabilitation settings", "Correctional system trauma", "Re-entry support", "Trauma-informed rehabilitation planning"],
         "3 hours", _module_quiz("Rehab", i, ["rehabilitation", "correctional trauma", "re-entry"]))
    for i in range(1, 7)
]


# ─────────────────────────────────────────────────────────────────────────────
# MASTER COURSE CONTENT DICTIONARY
# ─────────────────────────────────────────────────────────────────────────────
COURSE_CONTENT = {
    "ett-foundational-001": {"modules": ETT_FOUNDATIONAL},
    "cctsi-001":            {"modules": CCTSI_MODULES},
    "cctsf-001":            {"modules": CCTSF_MODULES},
    "cctsa-001":            {"modules": CCTSA_MODULES},
    "accts-001":            {"modules": ACCTS_MODULES},
    "cctsp-001":            {"modules": CCTSP_MODULES},
    "ctss-001":             {"modules": CTSS_MODULES},
    "crp-001":              {"modules": CRP_MODULES},
    "hospitality-001":      {"modules": HOSPITALITY_MODULES},
    "retreat-001":          {"modules": RETREAT_MODULES},
    "rehab-001":            {"modules": REHAB_MODULES},
}
